### ISSUE TITLE
Implement Detekt tool

### ISSUE THREAD

**Issue by fesave** [fesave/AAC-Board#6]
So that we all stick to the same coding standards, I think we should implement this tool having previously defined a common set of rules.

**Comment by cjimenezsanchez** [comment]
@fesave In order to upload the generated reports from the Detekt tool we need to allow writtings from Actions in the repository.

This repo configuration can only be made by the admin.

Please go to Settings/Actions/General and enable the read/write permissions under the Workflow Permissions section. See image attached for clarification.

![Image](https://user-images.githubusercontent.com/48380148/227792661-032aa21f-4dec-4c90-905e-6c6d46ad672c.PNG)

**Comment by fesave** [comment]
Changed! 👍
